### ISSUE TITLE
Bug when enumerating the seeds

### ISSUE THREAD

**Issue by FeiGSSS** [tjparmer/influence_maximization_BNs#1]
Hi,
it seems that when you enumerate all possible seeds [here](https://github.com/tjparmer/influence_maximization_BNs/blob/74e1f42c6f6f5b642b949537d70018b2b793c487/mean_field_computations.py#L319), with `seed_size=2`, it may results a seeds like `('en-1', 'en-0')` which is invalid cause you can not set node `en` as 0 and 1 at the same time in the beginning.

**Comment by tjparmer** [comment]
That is true: all seed filtering is done manually or in higher-level functions.  This will be fixed in a future version so that filtering is done in find_modules.
