### ISSUE TITLE
Bug caused by data type

### ISSUE THREAD

**Issue by FeiGSSS** [tjparmer/influence_maximization_BNs#2]
Hi,
The `row[2]` and `state` in this [line](https://github.com/tjparmer/influence_maximization_BNs/blob/74e1f42c6f6f5b642b949537d70018b2b793c487/mean_field_computations.py#L55) are of data type `str` and `int`, respectively, therefore, `row[2]!=state` will always be `True`, resulting `1-s` been returned. 
(I'm running on Python3)

**Comment by tjparmer** [comment]
I've confirmed that the code works for python 2.7, pandas 0.24.  The data type for row[2] is long and row[2]!=state evaluates correctly.  This may need to be updated for python3 and for pandas 1.4.

**Comment by FeiGSSS** [comment]
> I've confirmed that the code works for python 2.7, pandas 0.24. The data type for row[2] is long and row[2]!=state evaluates correctly. This may need to be updated for python3 and for pandas 1.4.

thanks
